title: ML & AI Systems Blog
description: Machine Learning, AI Systems, and Engineering
author:
  name: Vivek Verma

theme: minima
plugins:
  - jekyll-seo-tag

# Optional tweaks
show_excerpts: false   # hides repeated footer snippets
